In [4]:
import numpy as np

numOutputs = 3
numInputs = 2

print("These are the weights")
myWeights = np.random.uniform(-10, 10, (numOutputs, numInputs))
print(myWeights)
print()

print("These are the biases")
myBiases = np.random.uniform(-10, 10, (numOutputs, 1))
print(myBiases)
print()

print("using these two inputs")
myInputs = np.array([[5], [6]])
print(myInputs)
print()

print("Dot product of weights `dot` inputs")
res = myWeights.dot(myInputs)
print(res)
print()

print("Result of dot product + biases")
res = res + myBiases
print(res)
print()

from funcs import ActivationFunctions

for element in res:
    element[0] = ActivationFunctions.sigmoid(element[0])

print("Result after applying sigmoid")
print(res)

These are the weights
[[ 4.67631619  7.7437503 ]
 [ 2.0323769  -1.97112707]
 [-7.9824812   0.4173799 ]]

These are the biases
[[-6.70679706]
 [ 7.73047202]
 [ 6.05433027]]

using these two inputs
[[5]
 [6]]

Dot product of weights `dot` inputs
[[ 69.84408278]
 [ -1.6648779 ]
 [-37.40812658]]

Result of dot product + biases
[[ 63.13728571]
 [  6.06559411]
 [-31.35379631]]

Result after applying sigmoid
[[1.00000000e+00]
 [9.97683998e-01]
 [2.41668070e-14]]


In [7]:
from nnetwork import NeuralNetwork
from funcs import ActivationFunctions


nn = NeuralNetwork([2, 2], ActivationFunctions.sigmoid)
res = nn.forward(myInputs)

print(res)

[[1.56375523e-26]
 [1.00000000e+00]]
