In [15]:
import numpy as np

numOutputs = 3
numInputs = 2

print("These are the weights")
myWeights = np.random.uniform(-10, 10, (numOutputs, numInputs))
print(myWeights)
print()

print("These are the biases")
myBiases = np.random.uniform(-10, 10, (numOutputs, 1))
print(myBiases)
print()

print("using these two inputs")
myInputs = np.array([[5], [6]])
print(myInputs)
print()

print("Dot product of weights `dot` inputs")
res = myWeights.dot(myInputs)
print(res)
print()

print("Result of dot product + biases")
res = res + myBiases
print(res)
print()

from funcs import ActivationFunctions

for element in res:
    element[0] = ActivationFunctions.sigmoid(element[0])

print("Result after applying sigmoid")
print(res)

These are the weights
[[-2.24520446  8.51255995]
 [-4.7239926  -8.18751213]
 [-7.64785409 -5.0931955 ]]

These are the biases
[[-7.92360349]
 [-1.03983363]
 [-6.95852239]]

using these two inputs
[[5]
 [6]]

Dot product of weights `dot` inputs
[[ 39.8493374 ]
 [-72.74503582]
 [-68.79844346]]

Result of dot product + biases
[[ 31.92573391]
 [-73.78486945]
 [-75.75696586]]

Result after applying sigmoid
[[1.00000000e+00]
 [9.02897287e-33]
 [1.25651525e-33]]


In [17]:
from nnetwork import NeuralNetwork
from funcs import ActivationFunctions, CostFunctions

nn = NeuralNetwork([2, 2], ActivationFunctions.sigmoid, CostFunctions.mse_node_cost)
res = nn._get_cost(myInputs, np.array([[1.0], [0.0]], dtype=float))

print(res)

None
